# **Project Title : IDENTIFYING SPECIES OF FLOWERS BY CERTAIN MEASUREMENTS**

Importing Libraries

In [1]:
import numpy as np
import pandas as pd

Loading Dataset

In [3]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

Keys of Dataset



In [4]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


"DESCR" Key

In [12]:
print(iris_dataset['DESCR'][:200] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


"target_names"  Key

In [14]:
print("Target Names: {}".format(iris_dataset['target_names']))

Target Names: ['setosa' 'versicolor' 'virginica']


"feature_names"  Key

In [15]:
print("Feature Names: {}".format(iris_dataset['feature_names']))

Feature Names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Type of Data

In [16]:
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


Shape of Data

In [18]:
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


First 20 samples

In [27]:
print("First 20 rows:\n {}".format(iris_dataset['data'][0:20]))

First five rows:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]


"type" Key which contains species of each flower measured

In [26]:
print("Type of target: {}".format(type(iris_dataset['target'])))
print("\nShape of target: {}".format(iris_dataset['target'].shape))
print("\nTarget: \n {}".format(iris_dataset['target']))

Type of target: <class 'numpy.ndarray'>

Shape of target: (150,)

Target: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


 0 means setosa , 1 means versicolor , 2 means virginica

Training and Testing

In [31]:
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0
)

In [33]:
print("X_train Shape: {}".format(X_train.shape))
print("y_train Shape: {}".format(y_train.shape))
print("X_test Shape: {}".format(X_test.shape))
print("y_test Shape: {}".format(y_test.shape))

X_train Shape: (112, 4)
y_train Shape: (112,)
X_test Shape: (38, 4)
y_test Shape: (38,)


K-nearest Neighbour Model

In [34]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

Traning the Model with help of train dataset

In [36]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Testing the Model by giving a 2d array with 1 row in it

In [37]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


In [39]:
prediction = knn.predict(X_new)

print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name: ['setosa']


Evaluating the model by comparing predictions given by model with the actual values from test dataset

In [40]:
y_pred=knn.predict(X_test)
print("Test set predictions: {}".format(y_pred))

Test set predictions: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [48]:
print("comparison of both datasets: {}".format(np.mean(y_pred == y_test)))
print("Accuracy Percentage: {} %".format( 100*np.mean(y_pred == y_test)))

comparison of both datasets: 0.9736842105263158
Accuracy Percentage: 97.36842105263158 %


Thank you ShapeAI !!!